global:
  scrape_interval: 10s
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # - job_name: "SEW"

  #   # metrics_path defaults to '/metrics'
  #   # scheme defaults to 'http'.

  #   scrape_interval: 1s # poll very quickly for a more responsive demo
  #   static_configs:
  #     - targets: ["SRE:8080"]
  - job_name: "Oracle"
    scrape_interval: 1s
    static_configs:
      - targets: ["host.docker.internal:7195"]